[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "python3", "gcc"]

[phases.install]
cmds = [
  "npm install --no-package-lock",
  "cd server && npm install --no-package-lock"
]

[start]
cmd = "node server/index.js"
